const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

/**
 * Generates a professional PDF Action Plan for a government service.
 * @param {Object} data - { serviceName, actionPlan, userId }
 * @returns {Promise<string>} - Path to the generated PDF file.
 */
const generateActionPlanPDF = async (data) => {
    const { serviceName, actionPlan, userId } = data;
    const fileName = `ActionPlan_${userId}_${Date.now()}.pdf`;
    const filePath = path.join('uploads', fileName);

    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({
            margin: 50,
            size: 'A4'
        });

        const stream = fs.createWriteStream(filePath);
        doc.pipe(stream);

        // --- Header ---
        doc.fillColor('#1a5f7a')
           .fontSize(24)
           .text('RAASTA AI', { align: 'center' });

        doc.fontSize(12)
           .fillColor('#666666')
           .text('Your Personal Government Service Navigator', { align: 'center' })
           .moveDown();

        doc.rect(50, 100, 500, 2).fill('#1a5f7a');
        doc.moveDown();

        // --- Title ---
        doc.fillColor('#000000')
           .fontSize(18)
           .text(`Action Plan: ${serviceName}`, { underline: true })
           .moveDown();

        // --- Required Documents Section ---
        doc.fontSize(14)
           .fillColor('#1a5f7a')
           .text('Required Documents');

        doc.fontSize(12)
           .fillColor('#333333')
           .text('Please ensure you have the following documents ready:');

        actionPlan.documents.forEach(docum => {
            doc.text(`• ${docum}`, { indent: 20 });
        });
        doc.moveDown();

        // --- Steps Section ---
        doc.fontSize(14)
           .fillColor('#1a5f7a')
           .text('Step-by-Step Application Guide');

        doc.fontSize(12)
           .fillColor('#333333')
           .text('Follow these steps to complete your application:');

        actionPlan.steps.forEach(step => {
            doc.text(`${step.step}. ${step.action}`, { indent: 20 });
        });
        doc.moveDown();

        // --- Official Link ---
        if (actionPlan.officialUrl) {
            doc.fontSize(12)
               .fillColor('#0000EE')
               .text(`Official Portal: ${actionPlan.officialUrl}`, { underline: true });
        }
        doc.moveDown();

        // --- Footer ---
        doc.fontSize(10)
           .fillColor('#999999')
           .text(`Generated by Raasta AI on ${new Date().toLocaleDateString()}`, { align: 'right' });

        doc.end();

        stream.on('finish', () => resolve(filePath));
        stream.on('error', reject);
    });
};

module.exports = {
    generateActionPlanPDF
};
